import { PALETTE } from "./constants";

export const styles = {
  root: {
    minHeight: "100vh",
    background: `linear-gradient(135deg, ${PALETTE.bg[0]} 0%, ${PALETTE.bg[1]} 33%, ${PALETTE.bg[2]} 66%, ${PALETTE.bg[3]} 100%)`,
    backgroundAttachment: "fixed",
    fontFamily: "'Lexend', sans-serif",
    color: PALETTE.text,
    position: "relative",
    overflow: "hidden",
  },
  hero: {
    position: "relative",
    textAlign: "center",
    padding: "80px 24px 60px",
    zIndex: 2,
  },
  heroInner: {
    position: "relative",
    maxWidth: 800,
    margin: "0 auto",
  },
  heroPreTitle: {
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: "0.25em",
    color: PALETTE.textLight,
    marginBottom: 16,
    fontWeight: 500,
  },
  heroTitleWrapper: {
    position: "relative",
    display: "inline-block",
    marginBottom: 8,
  },
  heroBrush: {
    position: "absolute",
    bottom: -10,
    left: "5%",
    width: "90%",
    height: 40,
    opacity: 0.15,
    zIndex: -1,
    transformOrigin: "left",
    animation: "brushReveal 1.2s cubic-bezier(0.22, 1, 0.36, 1) forwards",
  },
  heroTitle: {
    fontFamily: "'Ultra', serif",
    fontSize: "clamp(42px, 8vw, 72px)",
    fontWeight: 900,
    color: PALETTE.text,
    lineHeight: 1,
    margin: 0,
  },
  heroName: {
    fontFamily: "'Delius Swash Caps', cursive",
    fontSize: "clamp(32px, 6vw, 48px)",
    color: PALETTE.purple,
    marginTop: 0,
  },
  heroDivider: {
    margin: "24px 0",
    display: "flex",
    justifyContent: "center",
  },
  heroSub: {
    fontSize: 14,
    color: PALETTE.textLight,
    letterSpacing: "0.15em",
    textTransform: "lowercase",
    marginBottom: 24,
  },
  heroCounter: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  countNum: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 32,
    fontWeight: 900,
    color: PALETTE.text,
  },
  countLabel: {
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: "0.15em",
    color: PALETTE.textLight,
    marginTop: -4,
  },
  addBtn: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    margin: "0 auto 48px",
    padding: "16px 32px",
    background: PALETTE.purple,
    color: "#FFF",
    border: "none",
    borderRadius: 0,
    fontFamily: "'Lexend', sans-serif",
    fontSize: 12,
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.2em",
    cursor: "pointer",
    boxShadow: "0 4px 15px rgba(107, 76, 138, 0.2)",
    transition: "all 0.3s cubic-bezier(0.22, 1, 0.36, 1)",
    position: "relative",
    overflow: "hidden",
    zIndex: 10,
  },
  grid: {
    // Legacy styles, now handled by .masonry-grid class
  },
  card: {
    borderRadius: 0,
    padding: "28px 24px 20px",
    position: "relative",
    border: "none",
    boxShadow: "none",
    transition: "transform 0.35s",
    cursor: "default",
    overflow: "visible",
    zIndex: 2,
    display: "flex",
    flexDirection: "column",
    width: "100%",
    height: "auto",
  },
  cardControls: {
    position: "absolute",
    top: -12,
    right: -12,
    display: "flex",
    gap: 6,
    zIndex: 20,
  },
  controlBtn: {
    width: 32,
    height: 32,
    borderRadius: 0,
    border: "1px solid #EEE",
    background: "#FFF",
    color: PALETTE.textMid,
    fontSize: 16,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.2s",
    boxShadow: "0 2px 8px rgba(0,0,0,0.05)",
  },
  cardSticker: {
    fontSize: 36,
    textAlign: "center",
    marginBottom: 16,
  },
  cardImageWrap: {
    borderRadius: 0,
    overflow: "hidden",
    flexShrink: 0,
    width: "100%",
    marginBottom: 16,
    border: "1px solid rgba(107,76,138,0.08)",
    cursor: "zoom-in",
  },
  cardImage: {
    width: "100%",
    display: "block",
    maxHeight: 200,
    objectFit: "cover",
  },
  cardMessage: {
    fontFamily: "'Quicksand', sans-serif",
    fontSize: 16,
    lineHeight: 1.75,
    color: "#1E1E2E",
    marginBottom: 16,
  },
  cardAuthor: {
    fontFamily: "'Delius', cursive",
    fontSize: 18,
    color: "#6B4C8A",
    marginBottom: 20,
  },
  reactionsRow: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    marginTop: "auto",
  },
  reactionBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    padding: "3px 8px",
    borderRadius: 0,
    border: "1px solid rgba(107,76,138,0.08)",
    background: "transparent",
    cursor: "pointer",
    fontSize: 14,
    transition: "all 0.2s cubic-bezier(0.22, 1, 0.36, 1)",
  },
  reactionBtnActive: {
    background: "rgba(107,76,138,0.06)",
    borderColor: "rgba(107,76,138,0.25)",
  },
  reactionCount: {
    fontSize: 11,
    fontWeight: 700,
    color: "#6B4C8A",
  },
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(30, 30, 46, 0.2)",
    backdropFilter: "blur(4px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    padding: 16,
  },
  modal: {
    background: "#FFFBFD",
    borderRadius: 0,
    width: "100%",
    maxWidth: 500,
    maxHeight: "90vh",
    overflow: "auto",
    padding: 40,
    boxShadow: "0 30px 90px rgba(0,0,0,0.15)",
    position: "relative",
  },
  modalHeader: {
    textAlign: "center",
    marginBottom: 32,
  },
  modalTitle: {
    fontFamily: "'Caveat', cursive",
    fontSize: 32,
    color: PALETTE.purple,
    margin: 0,
  },
  closeBtn: {
    position: "absolute",
    top: 20,
    right: 20,
    width: 32,
    height: 32,
    border: "none",
    background: "none",
    fontSize: 24,
    color: PALETTE.textLight,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  tabNav: {
    display: "flex",
    justifyContent: "center",
    gap: 24,
    marginBottom: 32,
    borderBottom: `1px solid ${PALETTE.lilac}44`,
  },
  tabBtn: {
    padding: "8px 4px",
    textTransform: "uppercase",
    fontSize: 11,
    letterSpacing: "0.15em",
    fontWeight: 600,
    color: PALETTE.textLight,
    background: "none",
    border: "none",
    cursor: "pointer",
    position: "relative",
    transition: "color 0.2s",
  },
  tabBtnActive: {
    color: PALETTE.text,
  },
  tabUnderline: {
    position: "absolute",
    bottom: -1,
    left: 0,
    width: "100%",
    height: 2,
    background: PALETTE.coral,
  },
  fieldGroup: {
    marginBottom: 24,
  },
  label: {
    display: "block",
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: "0.12em",
    color: PALETTE.textLight,
    marginBottom: 8,
  },
  input: {
    width: "100%",
    padding: "12px 0",
    border: "none",
    borderBottom: `1px solid ${PALETTE.lilac}`,
    background: "none",
    fontFamily: "'Lexend', sans-serif",
    fontSize: 15,
    color: PALETTE.text,
    borderRadius: 0,
    outline: "none",
    transition: "border-color 0.2s",
  },
  textarea: {
    width: "100%",
    padding: "12px 0",
    border: "none",
    borderBottom: `1px solid ${PALETTE.lilac}`,
    background: "none",
    fontFamily: "'Quicksand', sans-serif",
    fontSize: 16,
    color: PALETTE.text,
    borderRadius: 0,
    outline: "none",
    resize: "none",
  },
  uploadArea: {
    border: `1px dashed ${PALETTE.lilac}`,
    padding: 32,
    textAlign: "center",
    cursor: "pointer",
    color: PALETTE.textLight,
    fontSize: 14,
    transition: "all 0.2s",
  },
  submitBtn: {
    width: "100%",
    padding: "16px",
    background: PALETTE.purple,
    color: "#FFF",
    border: "none",
    borderRadius: 0,
    fontSize: 12,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.2em",
    fontFamily: "'Lexend', sans-serif",
    cursor: "pointer",
    transition: "all 0.3s",
  },
  footer: {
    padding: "60px 24px",
    textAlign: "center",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  footerDivider: {
    display: "flex",
    gap: 8,
    marginBottom: 20,
  },
  footerDot: {
    width: 6,
    height: 6,
    borderRadius: "50%",
  },
  footerText: {
    fontSize: 10,
    textTransform: "uppercase",
    letterSpacing: "0.25em",
    color: PALETTE.textLight,
  },
};
